### ISSUE TITLE
Att evolution code

### ISSUE THREAD

**Issue by rudahml** [MarcoWorms/poke#1]
Hey man, can you add this line on evolution folder?

"Shellder":{
    "level":"60",
    "to":"Cloyster"
}

Thanks so much...

Oh, and an idea, change all the levels from evolution like the meta game... You'll attract more players.

**Comment by MarcoWorms** [comment]
Thanks guys! Already merged the change, i'll push this to the production repo.

About the levels, they were exactly like the game but I changed them for balancing reasons. Feel free to change them and test, I will accept any PR that improves the gameplay.

**Comment by MarcoWorms** [comment]
Done, it's all on worms.io/poke :), thanks again for the contribution, feel free to make more issues/PRs 👍
