### ISSUE TITLE
Owned pokemon list problem

### ISSUE THREAD

**Issue by AMH9000** [MarcoWorms/poke#4]
When scrolling through my list of pokemon, i noticed that the last Pokemon in my list was Hitmonchan, but when I healed all of my pokemon, the last one to faint was Tangela.
So the list doesn't show all of your Pokemon now

**Comment by MarcoWorms** [comment]
@moriakaice made a pull request to fix that box but i think he accidentally broke it https://github.com/MarcoWorms/poke/pull/2

Maybe he can fix it, I can't work on that as of now, if no one fixes that I'll do it when i have time :)

**Comment by MarcoWorms** [comment]
I managed to find the error quickly and fixed it 👍

**Comment by moriakaice** [comment]
Sorry!

**Comment by MarcoWorms** [comment]
No problem! It was just ".container" default max height that was causing the trouble.

**Comment by AMH9000** [comment]
So will this be fixed in the next update?

**Comment by moriakaice** [comment]
It's already there. Still broken for you, @AMH9000?

**Comment by AMH9000** [comment]
It's fixed. I responded this late because I was just done for the day yesterday and got caught up in things today.
